---
dbType: mysql
jdbcUrl: jdbc:mysql://localhost:3306/eventuate?useSSL=false
dbHost: localhost
dbPort: 3306
dbUser: root
dbPass: rootpassword
dbName: eventuate
dbHistoryTopicName: db.history.topic
sourceTableName: MESSAGE
maximumPoolSize: 2
kafka: localhost:9092
zookeeper: localhost:2181
leadershipLockPath: /eventuatelocal/cdc/leader
mySqlBinLogClientName: MySqlBinLog
oldDbHistoryTopicName: eventuate.local.cdc.my-sql-connector.offset.storage
